services:
  db:
    image: mariadb:10.11.8
    environment:
      MYSQL_ROOT_PASSWORD: a1234
      MYSQL_DATABASE: ourcompanylunchauth
      MYSQL_USER: ourcompanylunchauthuser
      MYSQL_PASSWORD: a1234
    ports:
      - "3307:3306"
