spring:
  application:
    name: our-company-lunch-auth-server
  profiles:
    active: local
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9020
scheduler:
  clear-verification-code:
    cron: "0 0 3 * * *" # Run every day 03:00 AM
management:
  endpoints:
    web:
      exposure:
        include: "*"