spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3307/ourcompanylunchauth
    driver-class-name: org.mariadb.jdbc.Driver
    username: ourcompanylunchauthuser
    password:
jwt:
  secret:
  expired-in-hour: 24
business-server-url: http://localhost:8080