spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3307/ourcompanylunchauth
    driver-class-name: org.mariadb.jdbc.Driver
    username: ourcompanylunchauthuser
    password: a1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.springframework.security: trace
